### ISSUE TITLE
indentify headlines wrongly between ```

### ISSUE THREAD

**Issue by yanping** [demon386/SmartMarkdown#23]
when some codes between ``` contains # or ##,  SmartMarkdown take the lines as headlines, but they can be comments, for example , in R.  As following: 

![Imgur](http://i.imgur.com/lXHjQ3B.png)

**Comment by vovkkk** [comment]
It's purview of Markdown plugin (shipped with ST by default).
There is no such thing as fenced code in Markdown, if you know what I mean.

As workaround you can use another tmLanguage for Markdown instead of default one, e.g. [this one](https://raw.github.com/ttscoff/MarkdownEditing/master/Markdown.tmLanguage).
Mind you, default one should be overwrited if you want it to work right away, otherwise you'll need  to set syntax in ST from Markdown to Markdown (yea, it's confuse, I know).

**Comment by yanping** [comment]
@vovkkk Thank you very much

**Comment by stevepowell99** [comment]
Or you can just put a space before your comments - still works as a comment in R at least, and then doesn't get treated as a heading by smartmarkdown

**Comment by vovkkk** [comment]
Well, sure, whitespace is an option, but how about syntax highlighting?

![2014-10-31 02-07-55 untitled - sublime text 2](https://cloud.githubusercontent.com/assets/1975298/4851232/c20ea76c-6070-11e4-8e24-d6116f21b4d3.png)

it is knockdown plugin, fwiw; I think it doesn’t support R, would be relatively easy to add it though.

**Comment by demon386** [comment]
Thanks for these ideas. I will get back to work on those issues next week.
